name: PR Labeler

on:
  pull_request:
    types: [opened, edited]

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: Soomgo-Frontend/soomgo-frontend-actions/actions/pr-labeler@master